name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate changelog
      id: changelog
      run: |
        # Get the previous tag
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")
        
        # Generate changelog
        if [ -z "$PREV_TAG" ]; then
          CHANGELOG=$(git log --pretty=format:"* %s (%h)" --no-merges)
        else
          CHANGELOG=$(git log $PREV_TAG..HEAD --pretty=format:"* %s (%h)" --no-merges)
        fi
        
        # Set output
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## Changes
          ${{ steps.changelog.outputs.CHANGELOG }}
          
          ## Docker Images
          - `docker pull stephondoestech/unraid-config-guardian:${{ github.ref_name }}`
          - `docker pull stephondoestech/unraid-config-guardian:latest`
          
          ## Installation
          ```bash
          # Quick Unraid deployment
          docker run -d \
            --name unraid-config-guardian \
            --restart unless-stopped \
            -p 7842:8080 \
            -v /mnt/user/appdata/unraid-config-guardian:/config \
            -v /mnt/user/backups/unraid-docs:/output \
            -v /var/run/docker.sock:/var/run/docker.sock:ro \
            -v /boot:/boot:ro \
            -e PUID=99 -e PGID=100 -e TZ=America/New_York \
            stephondoestech/unraid-config-guardian:${{ github.ref_name }}
          ```
        draft: false
        prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'rc') }}